#! /bin/sh

case "$1" in
	start|"")
		echo -n "Starting miscellaneous setup: "

		# Regenerate shared library cache
		/sbin/ldconfig
		;;
	stop)
		;;
	*)
		echo "Usage: $0 {start|stop}" >&2
		exit 1
		;;
esac
